'use client';

import { useEffect, useState } from 'react';
import { useAuth } from '../../../providers';
import { Users, Search, TrendingUp, AlertCircle, ChevronRight, FileText, Download } from 'lucide-react';

type StudentRow = {
  id: string;
  name: string;
  class: string;
  mastery: number;
  engagementScore: number;
  recentActivity: string[];
  riskFlags: string[];
};

type AnalyticsData = {
  students: StudentRow[];
  atRiskStudents: StudentRow[];
  topPerformers: StudentRow[];
};

export default function TeacherStudentsPage() {
  const { user } = useAuth();
  const [data, setData] = useState<AnalyticsData | null>(null);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [selected, setSelected] = useState<StudentRow | null>(null);

  useEffect(() => {
    if (!user) return;
    (async () => {
      try {
        const r = await fetch(`/api/analytics/${user.id}`, { credentials: 'include' });
        if (r.ok) setData(await r.json());
      } finally {
        setLoading(false);
      }
    })();
  }, [user]);

  const allStudents: StudentRow[] = data
    ? [...(data.topPerformers || []), ...(data.atRiskStudents || []), ...(data.students || [])]
        .filter((s, i, arr) => arr.findIndex((x) => x.id === s.id) === i)
    : [];

  const filtered = allStudents.filter((s) =>
    s.name.toLowerCase().includes(search.toLowerCase()) ||
    s.class?.toLowerCase().includes(search.toLowerCase()),
  );

  const downloadReport = (student: StudentRow) => {
    const content = `
      <html>
        <head>
          <title>Student Report: ${student.name}</title>
          <style>
            body { font-family: system-ui, -apple-system, sans-serif; line-height: 1.5; color: #111827; max-width: 800px; margin: 40px auto; padding: 20px; }
            h1 { color: #4f46e5; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px; margin-bottom: 20px; }
            .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 30px; }
            .card { background: #f9fafb; padding: 15px; border-radius: 8px; border: 1px solid #e5e7eb; }
            h2 { font-size: 1.1rem; color: #374151; margin-top: 0; }
            .stat { font-size: 2rem; font-weight: bold; color: #4f46e5; }
            .risk { background: #fef2f2; border-color: #fca5a5; }
            .risk h2 { color: #b91c1c; }
            ul { margin: 0; padding-left: 20px; }
            li { margin-bottom: 5px; }
            .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; text-align: center; color: #6b7280; font-size: 0.875rem; }
          </style>
        </head>
        <body>
          <h1>Student Progress Report</h1>
          <p><strong>Student Name:</strong> ${student.name}</p>
          <p><strong>Grade/Class:</strong> ${student.class || 'N/A'}</p>
          <p><strong>Report Date:</strong> ${new Date().toLocaleDateString()}</p>
          
          <div class="grid">
            <div class="card">
              <h2>Subject Mastery</h2>
              <div class="stat">${Math.round((student.mastery || 0) * 100)}%</div>
            </div>
            <div class="card">
              <h2>Engagement Score</h2>
              <div class="stat">${Math.round((student.engagementScore || 0) * 100)}%</div>
            </div>
          </div>

          ${(student.riskFlags || []).length > 0 ? `
            <div class="card risk" style="margin-bottom: 20px;">
              <h2>Attention Required (Risk Flags)</h2>
              <ul>${student.riskFlags.map(f => `<li>${f}</li>`).join('')}</ul>
            </div>
          ` : ''}

          <div class="card">
            <h2>Recent Activity</h2>
            ${(student.recentActivity || []).length > 0 ? `
              <ul>${student.recentActivity.map(a => `<li>${a}</li>`).join('')}</ul>
            ` : '<p>No recent activity recorded.</p>'}
          </div>

          <div class="footer">
            Generated by SIH Platform for Parent-Teacher Meeting
          </div>
          <script>window.onload = function() { window.print(); }</script>
        </body>
      </html>
    `;

    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(content);
      printWindow.document.close();
    } else {
      alert("Please allow pop-ups to download the report.");
    }
  };

  return (
    <div className="p-4 md:p-6 lg:p-8 max-w-5xl mx-auto space-y-6 animate-fade-in">
      <header className="flex items-center gap-3">
        <div className="w-10 h-10 rounded-xl bg-indigo-100 flex items-center justify-center">
          <Users className="w-5 h-5 text-indigo-600" />
        </div>
        <div>
          <h1 className="font-display text-2xl font-bold text-gray-900">Student Directory</h1>
          <p className="text-sm text-gray-400 mt-1">Manage and track student performance</p>
        </div>
      </header>

      <div className="relative group">
        <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 group-focus-within:text-indigo-500 transition-colors" />
        <input
          type="text"
          placeholder="Search by student name or class…"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="input pl-10 py-3 w-full"
        />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Column: Student List */}
        <div className="lg:col-span-2 space-y-4">
          {loading ? (
            <div className="space-y-3">
              {Array.from({ length: 5 }).map((_, i) => <div key={i} className="skeleton h-16" />)}
            </div>
          ) : filtered.length === 0 ? (
            <div className="card p-10 text-center">
              <Users className="w-10 h-10 text-gray-300 mx-auto mb-3" />
              <p className="text-sm text-gray-400">No students found matching your search.</p>
            </div>
          ) : (
            <div className="card divide-y divide-gray-50 overflow-hidden">
              {filtered.map((s) => {
                const mastery = Math.round((s.mastery || 0) * 100);
                const atRisk = (s.riskFlags || []).length > 0;
                const isSelected = selected?.id === s.id;
                
                return (
                  <button
                    key={s.id}
                    onClick={() => setSelected(isSelected ? null : s)}
                    className={`w-full flex items-center gap-4 px-4 py-3.5 transition-colors text-left ${isSelected ? 'bg-indigo-50/50' : 'hover:bg-gray-50'}`}
                  >
                    <div className="w-10 h-10 rounded-full bg-gradient-to-br from-indigo-100 to-purple-100 flex items-center justify-center flex-shrink-0 text-indigo-700 font-bold text-sm">
                      {s.name.charAt(0).toUpperCase()}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2">
                        <p className="font-semibold text-gray-900 text-sm truncate">{s.name}</p>
                        {atRisk && <AlertCircle className="w-3.5 h-3.5 text-rose-500 flex-shrink-0" />}
                      </div>
                      <p className="text-xs text-gray-500 mt-0.5">Grade {s.class || '—'}</p>
                    </div>
                    <div className="text-right flex-shrink-0">
                      <p className="text-sm font-bold text-indigo-600 tabular-nums">{mastery}%</p>
                      <p className="text-[10px] text-gray-400 uppercase tracking-wide">Mastery</p>
                    </div>
                    <ChevronRight className={`w-4 h-4 text-gray-300 transition-transform duration-200 ${isSelected ? 'rotate-90 text-indigo-500' : ''}`} />
                  </button>
                );
              })}
            </div>
          )}
        </div>

        {/* Right Column: Student Details */}
        <div>
          {selected ? (
            <div className="card p-5 sticky top-6 animate-fade-in border-indigo-100 shadow-md">
              <div className="flex items-start justify-between mb-4">
                <div>
                  <h2 className="font-display font-bold text-gray-900 text-lg">{selected.name}</h2>
                  <p className="text-xs text-gray-500">Grade {selected.class || '—'}</p>
                </div>
                <button onClick={() => setSelected(null)} className="text-xs text-gray-400 hover:text-gray-700 font-medium px-2 py-1 bg-gray-100 rounded-lg">
                  Close
                </button>
              </div>
              
              <div className="grid grid-cols-2 gap-3 mb-5">
                <div className="stat-card p-3">
                  <p className="text-[10px] text-indigo-500 font-semibold uppercase tracking-wider mb-1">Mastery</p>
                  <p className="text-2xl font-bold text-indigo-700 tabular-nums">{Math.round((selected.mastery || 0) * 100)}%</p>
                </div>
                <div className="stat-card p-3 bg-emerald-50 border-emerald-100">
                  <p className="text-[10px] text-emerald-600 font-semibold uppercase tracking-wider mb-1">Engagement</p>
                  <p className="text-2xl font-bold text-emerald-700 tabular-nums">{Math.round((selected.engagementScore || 0) * 100)}%</p>
                </div>
              </div>
              
              {(selected.riskFlags || []).length > 0 && (
                <div className="bg-rose-50 rounded-xl p-4 border border-rose-100 mb-5">
                  <div className="flex items-center gap-1.5 mb-2">
                    <AlertCircle className="w-4 h-4 text-rose-600" />
                    <p className="text-xs font-bold text-rose-700">Needs Attention</p>
                  </div>
                  <ul className="space-y-1">
                    {selected.riskFlags.map((f, i) => (
                      <li key={i} className="text-xs text-rose-600/90 leading-snug flex items-start gap-1.5">
                        <span className="text-rose-400 mt-0.5">•</span> {f}
                      </li>
                    ))}
                  </ul>
                </div>
              )}
              
              <div className="mb-6">
                <p className="text-xs font-bold text-gray-900 mb-2">Recent Activity</p>
                {(selected.recentActivity || []).length > 0 ? (
                  <ul className="space-y-2">
                    {selected.recentActivity.slice(0, 5).map((a, i) => (
                      <li key={i} className="text-xs text-gray-600 flex items-start gap-2">
                        <div className="w-1 h-1 rounded-full bg-indigo-300 mt-1.5 flex-shrink-0" />
                        <span className="leading-relaxed">{a}</span>
                      </li>
                    ))}
                  </ul>
                ) : (
                  <p className="text-xs text-gray-400">No recent activity.</p>
                )}
              </div>

              <button 
                onClick={() => downloadReport(selected)}
                className="btn-primary w-full justify-center gap-2"
              >
                <Download className="w-4 h-4" />
                Export PDF Report
              </button>
            </div>
          ) : (
            <div className="card p-8 text-center sticky top-6 flex flex-col items-center justify-center min-h-[300px] border-dashed">
              <div className="w-12 h-12 rounded-2xl bg-gray-50 flex items-center justify-center mb-3">
                <Users className="w-6 h-6 text-gray-300" />
              </div>
              <p className="text-sm font-medium text-gray-900">No Student Selected</p>
              <p className="text-xs text-gray-400 mt-1">Select a student from the list to view details and generate reports.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
